// src/components/ComponentCard.tsx
import Link from 'next/link'

import { ComponentCard as ComponentCardInterface } from '@/interface/component'
import { componentSlug } from '@/services/utils/transformers'

type Props = {
  componentData: ComponentCardInterface
  categoryTitle: string
}

function ComponentCard({ componentData, categoryTitle }: Props) {
  const trueComponentSlug = componentSlug(
    componentData.slug,
    componentData.category
  )

  const componentCountPluralize =
    componentData.count > 1 ? 'Components' : 'Component'

  const componentCount = `${componentData.count} ${componentCountPluralize}`

  return (
    <Link href={`/components/${componentData.category}/${trueComponentSlug}`}>
      <a
        title={`Tailwind CSS ${categoryTitle} Components - ${componentData.title}`}
        className="group relative block h-full bg-white before:absolute before:inset-0 before:rounded-lg before:border-2 before:border-dashed before:border-gray-900 dark:bg-gray-900 dark:before:border-gray-700"
      >
        <div className="rounded-lg border-2 border-gray-900 bg-white transition group-hover:-translate-x-2 group-hover:-translate-y-2 dark:border-gray-700 dark:bg-gray-900">
          <div className="p-6">
            <span aria-hidden="true" role="img" className="text-xl">
              {componentData.emoji}
            </span>

            <h2 className="mt-4 text-lg font-medium text-gray-900 dark:text-white">
              {componentData.title}
            </h2>

            <p className="mt-1 text-xs text-gray-700 dark:text-gray-200">
              {componentCount}
            </p>
          </div>
        </div>
      </a>
    </Link>
  )
}

export default ComponentCard

// components/ComponentCard.vue
<script setup lang="ts">
const props = defineProps({
  component: {
    type: Object,
    required: true,
  },
})

const count = computed(() => {
  return props.component.components.reduce((total, component) => {
    return total + (component.dark ? 2 : 1)
  }, 0)
})
</script>

<template>
  <RouterLink :to="component.path">
    <div
      class="bg-white rounded-md shadow-sm border border-gray-300 p-4 sm:p-6 hover:shadow-none transition-shadow h-full"
    >
      <div class="flex items-center justify-between gap-4">
        <span aria-hidden="true" role="img" class="text-xl sm:text-2xl">
          {{ component.emoji }}
        </span>

        <CardTag v-if="component.tag" :tag="component.tag" />
      </div>

      <strong
        class="mt-4 block font-medium text-pretty text-gray-900 sm:text-lg"
      >
        {{ component.title }}
      </strong>

      <p class="mt-1 text-sm text-gray-700">
        {{ count }}
        Components
      </p>
    </div>
  </RouterLink>
</template>
