// components/ComponentCard.vue
<script setup lang="ts">
const props = defineProps({
  component: {
    type: Object,
    required: true,
  },
})

const count = computed(() => {
  return props.component.components.reduce((total, component) => {
    return total + (component.dark ? 2 : 1)
  }, 0)
})
</script>

<template>
  <RouterLink :to="component.path">
    <div
      class="bg-white rounded-md shadow-sm border border-gray-300 p-4 sm:p-6 hover:shadow-none transition-shadow h-full"
    >
      <div class="flex items-center justify-between gap-4">
        <span aria-hidden="true" role="img" class="text-xl sm:text-2xl">
          {{ component.emoji }}
        </span>

        <CardTag v-if="component.tag" :tag="component.tag" />
      </div>

      <strong
        class="mt-4 block font-medium text-pretty text-gray-900 sm:text-lg"
      >
        {{ component.title }}
      </strong>

      <p class="mt-1 text-sm text-gray-700">
        {{ count }}
        Components
      </p>
    </div>
  </RouterLink>
</template>

// src/components/ComponentCard.jsx
import Link from 'next/link'

export default function ComponentCard({ componentData }) {
  const componentCountPluralize =
    componentData.count > 1 ? 'Components' : 'Component'

  const componentCount = `${componentData.count} ${componentCountPluralize}`

  return (
    <Link href={`/components/${componentData.category}/${componentData.slug}`}>
      <div className="group relative block h-full bg-white before:absolute before:inset-0 before:rounded-lg before:border-2 before:border-dashed before:border-gray-900">
        <div className="rounded-lg border-2 border-gray-900 bg-white transition group-hover:-translate-y-2 ltr:group-hover:-translate-x-2 rtl:group-hover:translate-x-2">
          <div className="p-6">
            <span aria-hidden="true" role="img" className="text-xl">
              {componentData.emoji}
            </span>

            <h2 className="mt-4 text-lg font-medium text-gray-900">
              {componentData.title}
            </h2>

            <p className="mt-1 text-xs text-gray-700">{componentCount}</p>
          </div>
        </div>
      </div>
    </Link>
  )
}
