// app/blog/page.jsx
import matter from 'gray-matter'
import { promises as fs } from 'fs'
import { join } from 'path'

import Container from '@component/Container'
import HeroBanner from '@component/HeroBanner'
import BlogCard from '@component/BlogCard'

export const metadata = {
  title: 'Tailwind CSS Blog | HyperUI',
  description: 'Tips and tricks for using Tailwind CSS in your projects.',
  openGraph: {
    title: 'Tailwind CSS Blog | HyperUI',
    description: 'Tips and tricks for using Tailwind CSS in your projects.',
    url: 'https://www.hyperui.dev/',
    siteName: 'HyperUI',
    type: 'website',
    image: 'https://www.hyperui.dev/og.jpg',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Tailwind CSS Blog | HyperUI',
    description: 'Tips and tricks for using Tailwind CSS in your projects.',
  },
}

const postsPath = join(process.cwd(), '/src/data/posts')

async function getPosts() {
  const blogSlugs = await fs.readdir(postsPath)

  const blogPosts = await Promise.all(
    blogSlugs.map(async (blogSlug) => {
      const postPath = join(postsPath, blogSlug)
      const blogItem = await fs.readFile(postPath, 'utf-8')

      const { data: blogData } = matter(blogItem)

      return {
        title: blogData.title,
        slug: blogSlug.replace('.mdx', ''),
        date: blogData.date,
        emoji: blogData.emoji,
      }
    })
  )

  return blogPosts
}

export default async function Page() {
  const blogPosts = await getPosts()

  return (
    <>
      <HeroBanner
        title="Blog"
        subtitle="Tailwind CSS Blog with Tips and Tricks"
      >
        Learn Tailwind CSS tips and tricks that you can use in your work to help
        write cleaner, more maintainable code and help you be more productive.
      </HeroBanner>

      <Container classNames="py-8 lg:py-12">
        <ul className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
          {blogPosts.map((blogPost) => (
            <li key={blogPost.slug}>
              <BlogCard blogPost={blogPost} />
            </li>
          ))}
        </ul>
      </Container>
    </>
  )
}

// pages/blog/index.vue
<script setup lang="ts">
const route = useRoute()

const { data: posts } = await useAsyncData(route.path, () => {
  return queryCollection('blog')
    .select('path', 'title', 'emoji', 'date', 'tag')
    .order('date', 'ASC')
    .all()
})

// prettier-ignore
useSeoMeta({
  title: 'Tailwind CSS Blog',
  description: 'Tips and tricks for using Tailwind CSS in your projects.',
  ogTitle: 'Tailwind CSS Blog',
  ogDescription: 'Tips and tricks for using Tailwind CSS in your projects.',
  twitterTitle: 'Tailwind CSS Blog',
  twitterDescription: 'Tips and tricks for using Tailwind CSS in your projects.',
})
</script>

<template>
  <div>
    <PageBanner title="Blog" subtitle="Tailwind CSS Blog with Tips and Tricks">
      Learn Tailwind CSS tips and tricks that you can use in your work to help
      write cleaner, more maintainable code and help you be more productive.
    </PageBanner>

    <PageContainer class="py-8 lg:py-12">
      <ul class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <PostCard v-for="post in posts" :key="post.path" :post="post" />
      </ul>
    </PageContainer>
  </div>
</template>
